@url = https://8080-camilaborge-gradlesprin-z5raqjmysty.ws-us116.gitpod.io

GET {{url}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Vampire Survivors",
    "plataformas": [
        {"id": 2},
        {"id": 1}
    ]
}