@url = https://8080-camilaborge-gradlesprin-0osxgbr5lme.ws-us116.gitpod.io

GET {{url}}/plataformas

###

POST {{url}}/plataformas
Content-Type: application/json
 
{
    "nome": "mouse"
}
 
###
GET {{url}}/plataformas/8