@url = https://8080-camilaborge-gradlesprin-z5raqjmysty.ws-us116.gitpod.io

GET {{url}}/plataformas

###

POST {{url}}/plataformas
Content-Type: application/json
 
{
    "nome": "mobile"
}
 
###
GET {{url}}/plataformas/8